### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jjn037**
Thanks for your code, I get a worse results than the original py-faster-rcnn when I use the code,I have found you got a bbox normalize but not done a rpn normalize, so I add the rpn normalize in anchor target layer and get a right results.And I also add a agnostic in proposal target layer for running RFCN

### CODE REVIEW

**Comment by D-X-Y** [comment]
Hi, very thanks for your code. Would you mind to show me where the rpn use normalize in the official py-faster-rcnn code? I did not find the rpn_norm_mean in https://github.com/rbgirshick/py-faster-rcnn/blob/96dc9f1dea3087474d6da5a98879072901ee9bf9/lib/fast_rcnn/config.py 
Besides I found that you set the n_classes to 5, would you mind to explain the reason?

**Comment by jjn037** [comment]
Yes,they have not rpn_norm_mean,but rpn_norm_mean works and makes sense, proposal target layer tries to normalize bbox,and why not normalize bbox in  anchor target layer to keep the bbox processing uniformity，and n_class to 5 is my data class number, sorry.And agnostic has a bug and I am tring to fix,and you could use my code to comfire if it work

**Comment by D-X-Y** [comment]
I'm training the faster rcnn based on your commits. If the performance show better, I will merge into the dev branch. Thanks a lot!

**Comment by jjn037** [comment]
ok

**Pull request closed without merging**
